# Generated by Django 3.2.9 on 2021-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(),
        ),
    ]
